name = "{{HUGO_THEME}}"
license = "MIT"
licenselink = "https://github.com/ellerbrock/{{HUGO_THEME}}/blob/master/LICENSE"
description = "Responsive Open Source Theme Skeleton"
homepage = "https://github.com/ellerbrock/{{HUGO_THEME}}"
tags = [ "clean", "responsive", "minimal", "starter" ]
features = []
min_version = "0.24.1"

[author]
  name = "Maik Ellerbrock"
  homepage = "https://github.com/ellerbrock"

